# Generated by Django 2.2 on 2021-08-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='newwork',
            new_name='network',
        ),
    ]
