# Generated by Django 2.2 on 2021-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0002_auto_20210819_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='No value added'),
            preserve_default=False,
        ),
    ]
