# Generated by Django 2.2 on 2021-08-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0003_show_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='desc',
        ),
    ]
