# Generated by Django 2.2 on 2021-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0004_remove_show_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='no description added'),
            preserve_default=False,
        ),
    ]
