# Generated by Django 2.2 on 2021-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0005_show_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
